"""
Define all errors specific to Rootski Api.

As a pattern, errors used in Rootski Api define custom error classes for different error types. This
is useful in helping the calling application discern tool errors from those generated by upstream
tools.
"""


class RootskiApiError(Exception):
    """Base error class for Rootski Api."""


class ConfigurationError(RootskiApiError):
    """Raised when there is a configuration error."""


class AuthServiceError(RootskiApiError):
    """Raised when there is an error regarding the auth service"""


class MalformedTokenError(RootskiApiError):
    def __init__(self, token: str, stacktrace_error: Exception):
        self.token = token

    @property
    def message(self):
        return f"Error: malformed JWT Token. Got this error: {str(self)}" + f"\n\nToken: {str(self.token)}"


class BadBreakdownItemError(RootskiApiError):
    """Raised when a Breakdown Item is initialized incorrectly."""


class UserAlreadyRegisteredError(RootskiApiError):
    """Raised if an attempt is made to register a user that is already registered."""
