// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id:
    "us-west-2:b7670135-a073-489b-a745-493f6b4f7ca3",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_oH3VhGPjZ",
  aws_user_pools_web_client_id: "7etsid1jn9mu8d42qetqp11r1b",
  oauth: {
    domain: "auth-app-federated-authappenv.auth.us-west-2.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "http://localhost:3000/",
    redirectSignOut: "http://localhost:3000/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
